server {
    listen 80;
    root /usr/share/nginx/html;

    location = / { return 302 /QrCode_React/; }
    location = /QrCode_React { return 302 /QrCode_React/; }

    location /QrCode_React/ {
        try_files $uri $uri/ /QrCode_React/index.html;
    }

    location /QrCode_React/assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
